import "./globals.css";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ReactNode } from "react";

import { ReactQueryClientProvider } from "@/components/ReactQueryClientProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <ReactQueryClientProvider>
      <html lang="en" className="min-h-dvh h-full">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-dvh h-full flex flex-col bg-white text-gray-900`}
        >
          <AppRouterCacheProvider>{children}</AppRouterCacheProvider>
        </body>
      </html>
    </ReactQueryClientProvider>
  );
}
